### ISSUE TITLE
Allow opening event i Calendar App

### ISSUE THREAD

**Issue by johanhaleby** [deanishe/alfred-gcal#3]
It would be great if it would be possible to configure the workflow to open the events in the Calendar application instead of opening the website. I've tried specifying the calendar app in the configuration (using `CALENDAR_APP` workflow environment variable set to `/Applications/Calendar.app`) but while the app is opened it prompts one to subscribe to the event instead of showing its details:

![image](https://user-images.githubusercontent.com/187029/35265616-eb3c6040-0020-11e8-9552-78513a5f1003.png)

Is there a way to add support for showing the details instead?

**Comment by deanishe** [comment]
> but while the app is opened it prompts one to subscribe to the event instead of showing its details

Sure. As the help says, if you specify `CALENDAR_APP`, the workflow sends the Google Calendar *URL* to it. If you open a URL with Calendar.app, it assumes it's an .ical file you want to subscribe to.

`CALENDAR_APP` is for specifying an alternative *browser*. (In hindsight, I could have named the variable better.)

> Is there a way to add support for showing the details instead?

No, not in a useful way. There's no way to tell Calendar.app to show an event's details in any case.

You can tell Calendar.app to focus a specific event by UID, but it's tricky to do (all events in a series have the same UID) and is very, very slow because the AppleScript API is crappy.
