### ISSUE TITLE
The OAuth client was deleted.

### ISSUE THREAD

**Issue by goddardcm** [deanishe/alfred-gcal#46]
I'm getting errors when trying to access and add calendars. 

When trying to access (from `gdate workflow:log`)
```
07:28:47 ------------------- 2.549289ms -------------------
07:28:47 [ERROR] retrieve calendar list: Get https://www.googleapis.com/calendar/v3/users/me/calendarList?alt=json&prettyPrint=false: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error": "deleted_client",
  "error_description": "The OAuth client was deleted."
}
07:28:47 Get help at https://github.com/deanishe/alfred-gcal/issues
```

When trying to add:
![image](https://user-images.githubusercontent.com/959857/72268496-c4d83a80-35d6-11ea-860b-5ce4a74cc020.png)

I've checked and seemingly nothing has changed with the access granted:
![image](https://user-images.githubusercontent.com/959857/72268607-f3eeac00-35d6-11ea-96ee-439098a0f0c7.png)

**Comment by goddardcm** [comment]
Ah - I see you have a spicily-named recent release that will likely address this issue. Trying that out now.

I can fill another ticket, but `gdate workflow:update` seemed to be erring out, as well.

**Comment by goddardcm** [comment]
Update does seem to fix the OAuth Client issue, though Google is now saying that the OAuth app is unverified:

![image](https://user-images.githubusercontent.com/959857/72269128-edacff80-35d7-11ea-8d40-00626b216efc.png)

**Comment by deanishe** [comment]
> though Google is now saying that the OAuth app is unverified

It was already saying that before. It's because of Google's new "we care about privacy, lol" verification process. I had to change the client ID as part of the hoop-jumping required by it. You can still log in if you click "Advanced".

There's not much more I can do (or perhaps more accurately, am willing to do). I've given the workflow its own homepage, like they demanded, and changed the client ID, like they demanded. And they just told me to fuck off with this gem of a message:

```
We detected the following issue(s):

Homepage contains "google" in the domain
homepage_url: https://www.deanishe.net/alfred-gcal-workflow/
```

So I guess that's that. They're clearly retarded, and I'm sick of dealing with it.

People will just have to get their own client IDs to use the workflow once the 100-user limit is reached.

**Comment by goddardcm** [comment]
🤦‍♂ 

Appreciate all you've done thus far.
