### ISSUE TITLE
Error message: "Sign in with Google temporarily disabled for this app"

### ISSUE THREAD

**Issue by nickgraynews** [deanishe/alfred-gcal#48]
Hi! Big fan of your work and this workflow. Just wanted to let you know that I was experiencing issues after updating this morning. I get this message: "Sign in with Google temporarily disabled for this app" and then on a line below that, "This app has not been verified yet by Google in order to use Google Sign In."

**Comment by deanishe** [comment]
Thanks!

There should be an "Advanced" link at the bottom under the scary warning, via which you can still sign in. Also make sure you're using the latest version. I had to change the workflow's client ID (and may yet need to do it again…).

I'm trying to get the workflow verified, but Google keep rejecting it, most recently with this gem:

```
We detected the following issue(s):

Homepage contains "google" in the domain
homepage_url: https://www.deanishe.net/alfred-gcal-workflow/
```

**Comment by nickgraynews** [comment]
Thanks for a quick reply!
I don't get that "Advanced" link at the bottom of the scary sign in warning, so I am unable to use the Workflow.
Sorry to hear about the Google rejections. That sounds incredibly frustrating.
I really appreciate you working on this and troubleshooting in your spare time! THANK YOU!!

**Comment by deanishe** [comment]
~~It's seems Google have rectified their rectum–head relationship.~~

EDIT: No, they haven't

**Comment by deanishe** [comment]
I withdraw the above statement: The workflow is clearly still not working for a lot of people.

I'm at a loss as to what I can do to fix it. I've tried contacting Google, but as everyone knows, that's like banging your head against a wall.

The developer console says the workflow still needs to be verified:

![fucking-google-1](https://user-images.githubusercontent.com/747913/74277285-2ba05f00-4d0f-11ea-941f-ce6b871fc3a4.png)

But the "consent screen" page says it's fine:

![fucking-google-2](https://user-images.githubusercontent.com/747913/74277332-41158900-4d0f-11ea-9419-6ea0a0dd6924.png)

And doesn't allow me to (re)submit the workflow for verification:

![fucking-google-3](https://user-images.githubusercontent.com/747913/74277361-4ecb0e80-4d0f-11ea-9a6d-9110becd2fcd.png)

**Comment by yosevu** [comment]
Oh wow, that is frustrating. Are you able to use this workflow yourself @deanishe by getting to the screen with the "Advanced" button? Maybe there is another workaround?

**Comment by deanishe** [comment]
> Are you able to use this workflow yourself

Yes, thanks. It works perfectly for me…

![gcal-login](https://user-images.githubusercontent.com/747913/74510027-c5782f80-4efa-11ea-8a13-dd265043a114.png)

In any case, I'd just build it with a different client ID. I don't care about the warnings. The problem is that it's fairly complicated to get everything set up to build the workflow.

> Maybe there is another workaround?

Don't know. If any users have a paid Google account, you could try contacting support. They're pretty responsive to paid users.

**Comment by WybeBosch** [comment]
Just to clarify that the error happens After having chosen an account to login, and that they have indeed removed the "advanced" button text.

![alfred gcal auth issue](https://user-images.githubusercontent.com/40889930/75554996-b6859700-5a3b-11ea-965a-04739a57f9f7.png)

**Comment by pickettj** [comment]
Also love this workflow; had it working at first, but now I get a 401 error: "Error: deleted_client The OAuth client was deleted."
Perhaps this is part of the same issue, but, either way, is it possible to fix?

**Comment by jayroh** [comment]
@pickettj 👉  https://github.com/deanishe/alfred-gcal/issues/53

But then you'll probably run into the same issues as the above in this thread

**Comment by pickettj** [comment]
Thanks, @jayroh ! However, as you anticipated, I do indeed run into the same issue...

**Comment by nilsdrews** [comment]
I guess this has something to do with gcal in the path maybe? Can you modify this to something else and try again? I would love to get this added ...

**Comment by deanishe** [comment]
> I guess this has something to do with gcal in the path maybe?

No. It's Google being shit.

**Comment by AdamBD** [comment]
Maybe there is a way to create some list of signatures to submit a request for this allowance. Its an amazing utility here.

**Comment by deanishe** [comment]
If you have a paid Google account, you could try contacting support, I suppose. [My comment above contains the salient details](https://github.com/deanishe/alfred-gcal/issues/48#issuecomment-584842537).

**Comment by dergachev** [comment]
@deanishe for those of us willing to try building it on our own and setting up our own credentials, could you please consider writing up the steps? Ideally include whatever go compilation tools you'd need. I'm excited about this tool, I'm drowning in google calendar tabs.

**Comment by deanishe** [comment]
> could you please consider writing up the steps?

Seems like the best solution at this point. Obviously, Google can't be relied upon…

I'll think about the best way to do this. It'd probably be better to enable to workflow to use external credentials, rather than the built-in ones, instead of requiring users to build it for themselves.

Perhaps it will be possible to paste the JSON file into the configuration sheet, which would probably be the simplest solution for users.

**Comment by yosevu** [comment]
> Perhaps it will be possible to paste the JSON file into the configuration sheet, which would probably be the simplest solution for users.

Yes please 🙏

**Comment by Max604** [comment]
Does this mean there is alternative solution right now? And if so, how can we set it up for now. Thanks!

**Comment by kmf** [comment]
watching

**Comment by dfriedm** [comment]
Jumping on the bandwagon here, yaz please!

**Comment by deanishe** [comment]
> And if so, how can we set it up for now.

Yeah, you "just" need to set up your own Google project, get some credentials and build the workflow.

Sorry I haven't released a new version that can use your own creds yet: the coding is easy; I just don't want to write the bloody instructions for setting up a Google project.

For the build itself, the workflow is built with [mage](https://magefile.org/). You need to make a copy of `secret.go` called `secret_private.go` with the build tag `// +build private` and fill in the missing values, then run `mage link` in the project root directory to build the workflow and symlink it to your workflows folder, or `mage dist` to build an `.alfredworkflow` file.

The comment in `secret.go` saying you only need read permission is incorrect if you'd like to be able to add new events using `gnew`.

**Comment by AlaaSaadAbdo** [comment]
Hi! First of all thanks for the effort, I really like the workflow when it was working. I have a different set of problems. which is that my google account is managed since it belongs to an organization which means I can't set up my own projects in google.

Maybe this is an option, would it be possible to get the events from ical? and we sync ical to our google calendar? I understand that this might take a lot of time and effort. I just was wondering if it was an option.

Cheers!

**Comment by deanishe** [comment]
> Maybe this is an option, would it be possible to get the events from ical?

This is something I'm looking into. This whole fiasco has put me right off using Google's APIs.

I've [figured out the tricky part (getting the calendar events)](https://www.deanishe.net/post/2020/05/workflow-video-conferences/) already.

**Comment by AlaaSaadAbdo** [comment]
I'm not sure this is the right place to post this but I just tried the workflow 
(.vc) that you linked in your last comment and it said no access to the calendar although alfred has access to the calendar and calendar access works with other workflows

**Comment by Max604** [comment]
I've set up the build myself with mage but when try 'gcal' it keeps logging me in every single time and I have to press I trust this unverified app. The problem is alfred-gcal isn't remember the logged in account and isn't showing anything from the gcal itself.

How can I go about fixing this? Is it something in my Google Project settings?

The local website says for me 'ok'

**Comment by deanishe** [comment]
@Max604: I have no idea. You aren't giving me enough information to work with. You must at least post the contents of the log file (`gdate workflow:log`).

The "ok" means the workflow has received the access tokens, but perhaps you didn't give your app sufficient permissions.

You can enter `gdate workflow:cache` in Alfred to open the cache directory and check the credentials have been cached.

**Comment by Max604** [comment]
Interestingly after a few retries it has decided to 'just' work. I'll let you know if it happens again with the relevant logs and such.

**Comment by eli-jordan** [comment]
@deanishe Have you tried going through the [verification process](https://developers.google.com/apps-script/guides/client-verification)? 

There are a few requirements like needing to have docs on a domain you have proved to google that you own and such.

Its a PITA, but would be super valuable. This tool is excellent, and it would be a shame for it to not get the use it deserves :)

**Comment by eli-jordan** [comment]
Hmm... actually, I just realised the link I posted is for `apps-script` not sure if the requirements are the same

**Comment by deanishe** [comment]
> @deanishe Have you tried going through the verification process?

Yes. Read the thread. I posted [the bullshit answers Google is giving me](https://github.com/deanishe/alfred-gcal/issues/48#issuecomment-584842537) 5 months ago.

If you have a **paid** Google account, then please contact their support and ask them why they aren't letting you use an application that they say is verified. They sometimes listen to people with GSuite accounts.

**Comment by eli-jordan** [comment]
My workplace is a gsuite customer. I’ll check and see if I can get a support case opened for this.

**Comment by eli-jordan** [comment]
@deanishe Google support said that you should contact api-oauth-dev-verification@google.com to find out why the app is not considered verified. I have asked them to follow up on the reason using internal channels.

**Comment by deanishe** [comment]
Thanks, @eli-jordan. Your getting involved prompted me to go back and have another look at the Developer Console. Instead of the profoundly useless "verified and not verified", it now says there may be a problem with the scopes.

I'll release a new version in the next day or so with different scopes, and hopefully that one will work. It works for me, but that doesn't really tell me anything because it always did…

**Comment by deanishe** [comment]
Could somebody else test [this build](https://deanishe.net/alfred-workflows/Google-Calendar-View-0.5.0.alfredworkflow)?

If it works okay, I can make it an official release.

**Comment by ghost** [comment]
@deanishe I just downloaded it and it works for me :)

**Comment by deanishe** [comment]
@AlaaMansour Were you able to add a new account? Did you try adding a new event with `gnew`?

I think if you can add a new account, then it *should* be working okay.

**Comment by ghost** [comment]
@deanishe I added a new account and a new event with `gnew` it all works :)

**Comment by deanishe** [comment]
Awesome, I'll make a new release, then.

**Comment by eli-jordan** [comment]
@deanishe Thanks for the update, it seems to have fixed the verification error. I'm now seeing an error after approving access when redirected back to `http://127.0.0.1:61432/?state=...` I receive an error saying "bad state"

EDIT: I found a bunch of `gcal` processes running. After killing those, the redirect to localhost returned `ok`. However, the workflow still indicates that there is no account configured. Where can I look for logs to troubleshot this issue?

EDIT 2: After trying it a few more times. It eventually worked. I think there is a bug here, but not related to the issue reported in this issue.

**Comment by deanishe** [comment]
You can check the log file by entering `gdate workflow:log` into Alfred.

> I think there is a bug here, but not related to the issue reported in this issue.

What's most likely happening is that you have multiple authorisation processes running, but only the first one can grab the local port for the HTTP server. So Google is passing back the auth code for auth request Y to auth process X, and it consequently fails to retrieve the access tokens because it's using the wrong code for that request.

I'll add a timeout on the local auth server, so it doesn't hang around forever waiting for a code, but that will only make it less buggy.

The only real fix would be to split the authentication flow into a client-server system with a stateful server that can manage multiple auth requests at the same time. And that's overkill for a workflow, imo.

**Comment by eli-jordan** [comment]
> that's overkill for a workflow, imo.

Agreed

I don't think its a big problem, because if you get through the process once it doesn't affect day-to-day use.

Thanks again for the work on this workflow and fixing the verification issue 😀

**Comment by GregPetrov** [comment]
Thanks for fixing of Google Sign In and all your efforts!
Now it works perfect for me.
That is fantastic Alfred workflow!

**Comment by jayroh** [comment]
Holy crap, everything is working! Thank you so much @deanishe 

Just give word on a Patreon or get hooked up with github sponsors - and I'm there. I realize how much of a pain in the ass this was so you deserve the proper support 😄 

Thank you thank you!

**Comment by deanishe** [comment]
> Just give word on a Patreon or get hooked up with github sponsors - and I'm there

Very kind of you. I have [Paypal](https://www.paypal.me/deanishe) if that's an acceptable way to buy beer.
