### ISSUE TITLE
Record API errors and show them to the user

### ISSUE THREAD

**Issue by deanishe** [deanishe/alfred-gcal#7]
If authentication fails, the only indication is in the log file. Save error to file and show it to the user.

**Comment by nikivdev** [comment]
Hi @deanishe 

I wanted to add this change but I am curious what would you say the best way to work on some Go workflow is?

Let's say I cloned this repo to `~/go/src/github.com/deanishe/alfred-gcal` and ran `go get ./...` to get all the libraries. I suppose it doesn't have to be placed in `~/go` dir but `go get ./...` won't work otherwise.

What would I do next? I would think I would have to remove Alfred Gcal workflow I have now and use [your script to symlink](https://gist.github.com/deanishe/35faae3e7f89f629a94e) the workflow in ~/go to Alfred. Then use your [build script](https://gist.github.com/deanishe/b16f018119ef3fe951af) and then I am not quite sure. Basically I want to start hacking on a fork of the workflow without messing things up.

For my own workflows I use [these guidelines](https://github.com/nikitavoloboev/alfred-web-searches/blob/master/CONTRIBUTING.md#dependencies) and [this tool](https://godoc.org/github.com/jason0x43/go-alfred/alfred) that assumes that your source code is separate to the workflow items that go into `workflow` dir and where `alfred build` will put the binary into `workflow` I can run.

What is your process in developing workflows like I am curious? Also what would be the best way to forking and making changes to the workflow be?

Thank you.

**Comment by deanishe** [comment]
The workflow has its own build script at `bin/build`. That builds workflow in `./build`. That's the directory you link to Alfred.

I normally develop using [modd](https://github.com/cortesi/modd), which rebuilds the workflow when I change something.

This one isn't so straightforward, though, because you need [a Google API key](https://github.com/deanishe/alfred-gcal/blob/master/secret.go), which isn't in the repo.

The build script expects a `secret.go.private` file that is a copy of `secret.go`, but includes the API key. It swaps them before building, and back again afterwards.

**Comment by deanishe** [comment]
Have you looked into this, @nikitavoloboev, or should I do it?

**Comment by nikivdev** [comment]
@deanishe Have been quite busy as I got an internship recently and learning JS/React now.

Would be nice if you added the change. I also haven't looked at new AwGo changes. I did however look into [modd](https://github.com/cortesi/modd) and it's awesome.

**Comment by deanishe** [comment]
> I got an internship recently and learning JS/React now

Congratulations! Hope that works out well for you.

> Would be nice if you added the change

No problem. Will. do.
